# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1b9c61e4632a3466c19442ea136edb9fafd788a2ac681924bf87efb17a146adf83d60edab6b66590a4c5bd27b262d4476f9d433ae5bf48b7848e943d618a36

test:
  secret_key_base: fe0e7f32689f925737053679c3bfc815766d952c06c99366a0827368551cf1e3c33aeffa1338235454697f91b61ff78d7504f978e33699ec6eda9aad9dcc6c09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
